before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
script:
- mkdir _build
- pdflatex -output-directory _build terrainbook.tex
deploy:
  provider: releases
  api_key:
    secure: MkbPJcxiyW+Ok5RmdTJ/D+fEv1FcXm0oGi11N/OqVrJcyb1vcns2CU8OvziADvBZX5nimRMGdOqLguUqbUPTuwCRuJtZIwTPNH82snJMYsEeDy8p/5E+c7PQQ2/D/yIOxd4ldCpkbGhll5LLpvrtaz1o3O0lehjRPtr4U2DJzmHYTUBQrGsysOLdP0kpOSfpSRiVlZFWbODnNrrzDJ94x8qdgyJvQYUersHu3yU1OqC9J6ecHSNgvGoHiN3+2WIQQIIckoxmvdF4Ir7B8fPIZpkjwRyodqmqU/xgJ330o8RyyI9SF9qurv64TJsczj/jyDKaXjU52OfsBsk5swuoLfzO46gfLcfz0SM4ItAzFDyxO8hItQR1jS27U2hivvLTz+VsbdlOWu518KtxVKNkzboCfPpAz1SuVkH9KqKHAHk/9oMxA/4sUxTPExmKpN6ZNrNzONLM/20vKrSubgjB5Ff2q+6a3ettKka1d8U7v9yGE13kHeJuoaqFHDLllPVFRa3ulBIkmURglxCuGOFNGc6QCIUCvfOeeX3/vsg27VKnu/5m0y0U+wDq55uGgYoqwdRQyjjU49yXYammZkj+WwBupjgD2NDUDU20v+p5tzm7yoiitJRWGRU7C8+nm6QTyy2JioeIfuqEp3wu8mtqNN7ZpRVNpAjSTce5O4Hq2r0=
  file: "_build/terrainbook.pdf"
  skip_cleanup: true
  on:
    tags: true    

