name: Build LaTeX document on release

on:
 release:
  types: [created]
 

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: terrainbook.tex
          extra_packages: lastpage was ccicons mdframed needspace isodate algorithm2e todonotes fontawesome xpatch ifoddpage relsize cancel substr
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: terrainbook.pdf application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Upload pdf output as artifact
#         uses: actions/upload-artifact@master
#         with:
#           name: terrainbook-$GITHUB_SHA
#           path: terrainbook.pdf
